-- Expanded countries and committees

-- Countries: full list (195) with ISO codes
INSERT INTO countries (name, official_name, iso_code, region, aliases) VALUES
  ('Afghanistan', 'Afghanistan', 'AF', '', array[]::text[]),
  ('Albania', 'Albania', 'AL', '', array[]::text[]),
  ('Algeria', 'Algeria', 'DZ', '', array[]::text[]),
  ('Andorra', 'Andorra', 'AD', '', array[]::text[]),
  ('Angola', 'Angola', 'AO', '', array[]::text[]),
  ('Antigua and Barbuda', 'Antigua and Barbuda', 'AG', '', array[]::text[]),
  ('Argentina', 'Argentina', 'AR', '', array[]::text[]),
  ('Armenia', 'Armenia', 'AM', '', array[]::text[]),
  ('Australia', 'Australia', 'AU', '', array[]::text[]),
  ('Austria', 'Austria', 'AT', '', array[]::text[]),
  ('Azerbaijan', 'Azerbaijan', 'AZ', '', array[]::text[]),
  ('Bahamas', 'Bahamas', 'BS', '', array[]::text[]),
  ('Bahrain', 'Bahrain', 'BH', '', array[]::text[]),
  ('Bangladesh', 'Bangladesh', 'BD', '', array[]::text[]),
  ('Barbados', 'Barbados', 'BB', '', array[]::text[]),
  ('Belarus', 'Belarus', 'BY', '', array[]::text[]),
  ('Belgium', 'Belgium', 'BE', '', array[]::text[]),
  ('Belize', 'Belize', 'BZ', '', array[]::text[]),
  ('Benin', 'Benin', 'BJ', '', array[]::text[]),
  ('Bhutan', 'Bhutan', 'BT', '', array[]::text[]),
  ('Bolivia', 'Bolivia', 'BO', '', array[]::text[]),
  ('Bosnia and Herzegovina', 'Bosnia and Herzegovina', 'BA', '', array[]::text[]),
  ('Botswana', 'Botswana', 'BW', '', array[]::text[]),
  ('Brazil', 'Brazil', 'BR', '', array[]::text[]),
  ('Brunei', 'Brunei', 'BN', '', array[]::text[]),
  ('Bulgaria', 'Bulgaria', 'BG', '', array[]::text[]),
  ('Burkina Faso', 'Burkina Faso', 'BF', '', array[]::text[]),
  ('Burundi', 'Burundi', 'BI', '', array[]::text[]),
  ('Cabo Verde', 'Cabo Verde', 'CV', '', array[]::text[]),
  ('Cambodia', 'Cambodia', 'KH', '', array[]::text[]),
  ('Cameroon', 'Cameroon', 'CM', '', array[]::text[]),
  ('Canada', 'Canada', 'CA', '', array[]::text[]),
  ('Central African Republic', 'Central African Republic', 'CF', '', array[]::text[]),
  ('Chad', 'Chad', 'TD', '', array[]::text[]),
  ('Chile', 'Chile', 'CL', '', array[]::text[]),
  ('China', 'China', 'CN', '', array[]::text[]),
  ('Colombia', 'Colombia', 'CO', '', array[]::text[]),
  ('Comoros', 'Comoros', 'KM', '', array[]::text[]),
  ('Congo', 'Congo', 'CG', '', array[]::text[]),
  ('Costa Rica', 'Costa Rica', 'CR', '', array[]::text[]),
  ('Côte d''Ivoire', 'Côte d''Ivoire', 'CI', '', array[]::text[]),
  ('Croatia', 'Croatia', 'HR', '', array[]::text[]),
  ('Cuba', 'Cuba', 'CU', '', array[]::text[]),
  ('Cyprus', 'Cyprus', 'CY', '', array[]::text[]),
  ('Czech Republic', 'Czech Republic', 'CZ', '', array[]::text[]),
  ('Democratic Republic of the Congo', 'Democratic Republic of the Congo', 'CD', '', array[]::text[]),
  ('Denmark', 'Denmark', 'DK', '', array[]::text[]),
  ('Djibouti', 'Djibouti', 'DJ', '', array[]::text[]),
  ('Dominica', 'Dominica', 'DM', '', array[]::text[]),
  ('Dominican Republic', 'Dominican Republic', 'DO', '', array[]::text[]),
  ('Ecuador', 'Ecuador', 'EC', '', array[]::text[]),
  ('Egypt', 'Egypt', 'EG', '', array[]::text[]),
  ('El Salvador', 'El Salvador', 'SV', '', array[]::text[]),
  ('Equatorial Guinea', 'Equatorial Guinea', 'GQ', '', array[]::text[]),
  ('Eritrea', 'Eritrea', 'ER', '', array[]::text[]),
  ('Estonia', 'Estonia', 'EE', '', array[]::text[]),
  ('Eswatini', 'Eswatini', 'SZ', '', array[]::text[]),
  ('Ethiopia', 'Ethiopia', 'ET', '', array[]::text[]),
  ('Fiji', 'Fiji', 'FJ', '', array[]::text[]),
  ('Finland', 'Finland', 'FI', '', array[]::text[]),
  ('France', 'France', 'FR', '', array[]::text[]),
  ('Gabon', 'Gabon', 'GA', '', array[]::text[]),
  ('Gambia', 'Gambia', 'GM', '', array[]::text[]),
  ('Georgia', 'Georgia', 'GE', '', array[]::text[]),
  ('Germany', 'Germany', 'DE', '', array[]::text[]),
  ('Ghana', 'Ghana', 'GH', '', array[]::text[]),
  ('Greece', 'Greece', 'GR', '', array[]::text[]),
  ('Grenada', 'Grenada', 'GD', '', array[]::text[]),
  ('Guatemala', 'Guatemala', 'GT', '', array[]::text[]),
  ('Guinea', 'Guinea', 'GN', '', array[]::text[]),
  ('Guinea-Bissau', 'Guinea-Bissau', 'GW', '', array[]::text[]),
  ('Guyana', 'Guyana', 'GY', '', array[]::text[]),
  ('Haiti', 'Haiti', 'HT', '', array[]::text[]),
  ('Honduras', 'Honduras', 'HN', '', array[]::text[]),
  ('Hungary', 'Hungary', 'HU', '', array[]::text[]),
  ('Iceland', 'Iceland', 'IS', '', array[]::text[]),
  ('India', 'India', 'IN', '', array[]::text[]),
  ('Indonesia', 'Indonesia', 'ID', '', array[]::text[]),
  ('Iran', 'Iran', 'IR', '', array[]::text[]),
  ('Iraq', 'Iraq', 'IQ', '', array[]::text[]),
  ('Ireland', 'Ireland', 'IE', '', array[]::text[]),
  ('Israel', 'Israel', 'IL', '', array[]::text[]),
  ('Italy', 'Italy', 'IT', '', array[]::text[]),
  ('Jamaica', 'Jamaica', 'JM', '', array[]::text[]),
  ('Japan', 'Japan', 'JP', '', array[]::text[]),
  ('Jordan', 'Jordan', 'JO', '', array[]::text[]),
  ('Kazakhstan', 'Kazakhstan', 'KZ', '', array[]::text[]),
  ('Kenya', 'Kenya', 'KE', '', array[]::text[]),
  ('Kiribati', 'Kiribati', 'KI', '', array[]::text[]),
  ('Kuwait', 'Kuwait', 'KW', '', array[]::text[]),
  ('Kyrgyzstan', 'Kyrgyzstan', 'KG', '', array[]::text[]),
  ('Laos', 'Laos', 'LA', '', array[]::text[]),
  ('Latvia', 'Latvia', 'LV', '', array[]::text[]),
  ('Lebanon', 'Lebanon', 'LB', '', array[]::text[]),
  ('Lesotho', 'Lesotho', 'LS', '', array[]::text[]),
  ('Liberia', 'Liberia', 'LR', '', array[]::text[]),
  ('Libya', 'Libya', 'LY', '', array[]::text[]),
  ('Liechtenstein', 'Liechtenstein', 'LI', '', array[]::text[]),
  ('Lithuania', 'Lithuania', 'LT', '', array[]::text[]),
  ('Luxembourg', 'Luxembourg', 'LU', '', array[]::text[]),
  ('Madagascar', 'Madagascar', 'MG', '', array[]::text[]),
  ('Malawi', 'Malawi', 'MW', '', array[]::text[]),
  ('Malaysia', 'Malaysia', 'MY', '', array[]::text[]),
  ('Maldives', 'Maldives', 'MV', '', array[]::text[]),
  ('Mali', 'Mali', 'ML', '', array[]::text[]),
  ('Malta', 'Malta', 'MT', '', array[]::text[]),
  ('Marshall Islands', 'Marshall Islands', 'MH', '', array[]::text[]),
  ('Mauritania', 'Mauritania', 'MR', '', array[]::text[]),
  ('Mauritius', 'Mauritius', 'MU', '', array[]::text[]),
  ('Mexico', 'Mexico', 'MX', '', array[]::text[]),
  ('Micronesia', 'Micronesia', 'FM', '', array[]::text[]),
  ('Moldova', 'Moldova', 'MD', '', array[]::text[]),
  ('Monaco', 'Monaco', 'MC', '', array[]::text[]),
  ('Mongolia', 'Mongolia', 'MN', '', array[]::text[]),
  ('Montenegro', 'Montenegro', 'ME', '', array[]::text[]),
  ('Morocco', 'Morocco', 'MA', '', array[]::text[]),
  ('Mozambique', 'Mozambique', 'MZ', '', array[]::text[]),
  ('Myanmar', 'Myanmar', 'MM', '', array[]::text[]),
  ('Namibia', 'Namibia', 'NA', '', array[]::text[]),
  ('Nauru', 'Nauru', 'NR', '', array[]::text[]),
  ('Nepal', 'Nepal', 'NP', '', array[]::text[]),
  ('Netherlands', 'Netherlands', 'NL', '', array[]::text[]),
  ('New Zealand', 'New Zealand', 'NZ', '', array[]::text[]),
  ('Nicaragua', 'Nicaragua', 'NI', '', array[]::text[]),
  ('Niger', 'Niger', 'NE', '', array[]::text[]),
  ('Nigeria', 'Nigeria', 'NG', '', array[]::text[]),
  ('North Korea', 'North Korea', 'KP', '', array[]::text[]),
  ('North Macedonia', 'North Macedonia', 'MK', '', array[]::text[]),
  ('Norway', 'Norway', 'NO', '', array[]::text[]),
  ('Oman', 'Oman', 'OM', '', array[]::text[]),
  ('Pakistan', 'Pakistan', 'PK', '', array[]::text[]),
  ('Palau', 'Palau', 'PW', '', array[]::text[]),
  ('Palestine', 'Palestine', 'PS', '', array[]::text[]),
  ('Panama', 'Panama', 'PA', '', array[]::text[]),
  ('Papua New Guinea', 'Papua New Guinea', 'PG', '', array[]::text[]),
  ('Paraguay', 'Paraguay', 'PY', '', array[]::text[]),
  ('Peru', 'Peru', 'PE', '', array[]::text[]),
  ('Philippines', 'Philippines', 'PH', '', array[]::text[]),
  ('Poland', 'Poland', 'PL', '', array[]::text[]),
  ('Portugal', 'Portugal', 'PT', '', array[]::text[]),
  ('Qatar', 'Qatar', 'QA', '', array[]::text[]),
  ('Romania', 'Romania', 'RO', '', array[]::text[]),
  ('Russia', 'Russia', 'RU', '', array[]::text[]),
  ('Rwanda', 'Rwanda', 'RW', '', array[]::text[]),
  ('Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'KN', '', array[]::text[]),
  ('Saint Lucia', 'Saint Lucia', 'LC', '', array[]::text[]),
  ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines', 'VC', '', array[]::text[]),
  ('Samoa', 'Samoa', 'WS', '', array[]::text[]),
  ('San Marino', 'San Marino', 'SM', '', array[]::text[]),
  ('Sao Tome and Principe', 'Sao Tome and Principe', 'ST', '', array[]::text[]),
  ('Saudi Arabia', 'Saudi Arabia', 'SA', '', array[]::text[]),
  ('Senegal', 'Senegal', 'SN', '', array[]::text[]),
  ('Serbia', 'Serbia', 'RS', '', array[]::text[]),
  ('Seychelles', 'Seychelles', 'SC', '', array[]::text[]),
  ('Sierra Leone', 'Sierra Leone', 'SL', '', array[]::text[]),
  ('Singapore', 'Singapore', 'SG', '', array[]::text[]),
  ('Slovakia', 'Slovakia', 'SK', '', array[]::text[]),
  ('Slovenia', 'Slovenia', 'SI', '', array[]::text[]),
  ('Solomon Islands', 'Solomon Islands', 'SB', '', array[]::text[]),
  ('Somalia', 'Somalia', 'SO', '', array[]::text[]),
  ('South Africa', 'South Africa', 'ZA', '', array[]::text[]),
  ('South Korea', 'South Korea', 'KR', '', array[]::text[]),
  ('South Sudan', 'South Sudan', 'SS', '', array[]::text[]),
  ('Spain', 'Spain', 'ES', '', array[]::text[]),
  ('Sri Lanka', 'Sri Lanka', 'LK', '', array[]::text[]),
  ('Sudan', 'Sudan', 'SD', '', array[]::text[]),
  ('Suriname', 'Suriname', 'SR', '', array[]::text[]),
  ('Sweden', 'Sweden', 'SE', '', array[]::text[]),
  ('Switzerland', 'Switzerland', 'CH', '', array[]::text[]),
  ('Syria', 'Syria', 'SY', '', array[]::text[]),
  ('Tajikistan', 'Tajikistan', 'TJ', '', array[]::text[]),
  ('Tanzania', 'Tanzania', 'TZ', '', array[]::text[]),
  ('Thailand', 'Thailand', 'TH', '', array[]::text[]),
  ('Timor-Leste', 'Timor-Leste', 'TL', '', array[]::text[]),
  ('Togo', 'Togo', 'TG', '', array[]::text[]),
  ('Tonga', 'Tonga', 'TO', '', array[]::text[]),
  ('Trinidad and Tobago', 'Trinidad and Tobago', 'TT', '', array[]::text[]),
  ('Tunisia', 'Tunisia', 'TN', '', array[]::text[]),
  ('Turkey', 'Turkey', 'TR', '', array[]::text[]),
  ('Turkmenistan', 'Turkmenistan', 'TM', '', array[]::text[]),
  ('Tuvalu', 'Tuvalu', 'TV', '', array[]::text[]),
  ('Uganda', 'Uganda', 'UG', '', array[]::text[]),
  ('Ukraine', 'Ukraine', 'UA', '', array[]::text[]),
  ('United Arab Emirates', 'United Arab Emirates', 'AE', '', array[]::text[]),
  ('United Kingdom', 'United Kingdom', 'GB', '', array[]::text[]),
  ('United States', 'United States', 'US', '', array[]::text[]),
  ('Uruguay', 'Uruguay', 'UY', '', array[]::text[]),
  ('Uzbekistan', 'Uzbekistan', 'UZ', '', array[]::text[]),
  ('Vanuatu', 'Vanuatu', 'VU', '', array[]::text[]),
  ('Vatican City', 'Vatican City', 'VA', '', array[]::text[]),
  ('Venezuela', 'Venezuela', 'VE', '', array[]::text[]),
  ('Vietnam', 'Vietnam', 'VN', '', array[]::text[]),
  ('Yemen', 'Yemen', 'YE', '', array[]::text[]),
  ('Zambia', 'Zambia', 'ZM', '', array[]::text[]),
  ('Zimbabwe', 'Zimbabwe', 'ZW', '', array[]::text[])
ON CONFLICT (iso_code) DO NOTHING;

-- Additional committees (UNHCR, ICPC/Interpol, etc.)
INSERT INTO committees (id, name, abbreviation, description, type, mandate, powers, typical_topics, procedural_rules) VALUES
  ('00000000-0000-0000-0000-000000000006',
   'UN High Commissioner for Refugees', 'UNHCR',
   'Protection and assistance for refugees worldwide',
   'Specialized Agency',
   'Lead international action to protect refugees and resolve refugee problems (UNGA Res 428)',
   array['Refugee status determination','Durable solutions','Emergency response','Statelessness prevention'],
   array['Refugee protection','Asylum procedures','Internal displacement','Stateless persons'],
   'Executive Committee (ExCom) annual sessions; consensus-based decisions'
  ),
  ('00000000-0000-0000-0000-000000000007',
   'International Criminal Police Organization', 'INTERPOL',
   'Global police cooperation and crime prevention',
   'Intergovernmental Organization',
   'Ensure widest possible mutual assistance between criminal police authorities (INTERPOL Constitution Art 2)',
   array['Red Notices','Diffusions','I-24/7 database','Capacity building'],
   array['Transnational crime','Terrorism','Cybercrime','Human trafficking','Drug trafficking'],
   'General Assembly annual; Executive Committee; Secretary General'
  ),
  ('00000000-0000-0000-0000-000000000008',
   'World Health Organization', 'WHO',
   'International public health coordination',
   'Specialized Agency',
   'Attainment by all peoples of the highest possible level of health (WHO Constitution)',
   array['International Health Regulations','Health emergencies','Normative guidance','Technical cooperation'],
   array['Pandemic preparedness','Disease eradication','Health systems','Universal health coverage'],
   'World Health Assembly; Executive Board; Director-General'
  ),
  ('00000000-0000-0000-0000-000000000009',
   'UN Office on Drugs and Crime', 'UNODC',
   'Combat drugs, crime, and terrorism',
   'Secretariat Office',
   'Guardian of UN conventions against drugs, crime, corruption, terrorism',
   array['Convention monitoring','Technical assistance','Research analysis','Legal tools'],
   array['Drug control','Organized crime','Corruption','Terrorism prevention','Trafficking in persons'],
   'Commission on Narcotic Drugs; Commission on Crime Prevention Criminal Justice'
  ),
  ('00000000-0000-0000-0000-000000000010',
   'UN Development Programme', 'UNDP',
   'Eradicate poverty, reduce inequalities',
   'Fund/Programme',
   'Help countries achieve sustainable development (UNGA Res 2029)',
   array['Policy advice','Capacity development','Advocacy','Grant financing'],
   array['SDG implementation','Governance','Climate action','Crisis recovery','Gender equality'],
   'Executive Board; Administrator; Regional bureaux'
  )
ON CONFLICT (id) DO NOTHING;

-- Additional agendas for new committees
INSERT INTO agendas (id, title, description, committee_id, keywords, relevant_treaties, relevant_un_bodies) VALUES
  (gen_random_uuid(),
   'Global Compact on Refugees implementation',
   'Review progress on burden-sharing and responsibility-sharing for refugee protection',
   '00000000-0000-0000-0000-000000000006',
   array['refugees','global compact','burden-sharing','protection'],
   array['1951 Refugee Convention','1967 Protocol','Global Compact on Refugees'],
   array['UNHCR','UNGA','ECOSOC']
  ),
  (gen_random_uuid(),
   'Combating transnational organized crime',
   'Strengthen international cooperation against criminal networks',
   '00000000-0000-0000-0000-000000000007',
   array['organized crime','Interpol','Red Notice','cooperation'],
   array['UNTOC','Palermo Protocols'],
   array['INTERPOL','UNODC','UNGA']
  ),
  (gen_random_uuid(),
   'Pandemic preparedness and response',
   'Lessons from COVID-19 for future health emergencies',
   '00000000-0000-0000-0000-000000000008',
   array['pandemic','health security','IHR','WHO reform'],
   array['International Health Regulations (2005)','Pandemic Treaty (negotiating)'],
   array['WHO','WHA','UNGA']
  ),
  (gen_random_uuid(),
   'Addressing synthetic drug markets',
   'Tackle rising synthetic opioid and stimulant trafficking',
   '00000000-0000-0000-0000-000000000009',
   array['synthetic drugs','fentanyl','trafficking','precursors'],
   array['1961 Single Convention','1971 Psychotropic Convention','1988 Trafficking Convention'],
   array['UNODC','CND','WHO']
  ),
  (gen_random_uuid(),
   'Financing for Sustainable Development Goals',
   'Mobilize resources for 2030 Agenda implementation',
   '00000000-0000-0000-0000-000000000010',
   array['SDG financing','development aid','domestic resources','private sector'],
   array['Addis Ababa Action Agenda','2030 Agenda'],
   array['UNDP','ECOSOC','UNGA','World Bank','IMF']
  )
ON CONFLICT (id) DO NOTHING;